packages:
  - extensions/*
  - skills/*
  - themes/*

overrides:
  '@earendil-works/pi-ai': $@earendil-works/pi-ai
  '@earendil-works/pi-coding-agent': $@earendil-works/pi-coding-agent
  '@earendil-works/pi-tui': $@earendil-works/pi-tui

onlyBuiltDependencies:
  - '@google/genai'
  - esbuild
  - fff-router
  - koffi
  - protobufjs
