packages:
  - extensions/*
  - packages/*
  - skills/*
  - themes/*

overrides:
  '@earendil-works/pi-ai': 0.80.2
  '@earendil-works/pi-coding-agent': 0.80.2
  '@earendil-works/pi-tui': 0.80.2

onlyBuiltDependencies:
  - '@google/genai'
  - esbuild
  - fff-router
  - koffi
  - protobufjs
