packages:
  - extensions/*
  - packages/*
  - skills/*
  - themes/*

overrides:
  '@earendil-works/pi-agent-core': 0.81.1
  '@earendil-works/pi-ai': 0.81.1
  '@earendil-works/pi-coding-agent': 0.81.1
  '@earendil-works/pi-tui': 0.81.1

minimumReleaseAgeExclude:
  - '@earendil-works/pi-*'

allowBuilds:
  '@google/genai': true
  esbuild: true
  fff-router: true
  fff-router@https://codeload.github.com/unstableneutron/fff-router/tar.gz/599ee0409d113573c003d419c3702ffc3b0d3a1f: true
  koffi: true
  protobufjs: true
